version: '3'

services:
  tutoria_ms:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    #command: python manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - "5002:8000"
    depends_on: 
      - tutoria_db
  tutoria_db:
    image: postgres
    ports:
      - "3002:5432"