# Generated by Django 2.1.4 on 2019-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.TextField(default='')),
                ('descripcion', models.TextField(blank=True)),
                ('cupos', models.SmallIntegerField()),
                ('idtutor', models.SmallIntegerField()),
                ('idtoken', models.TextField(blank=True)),
            ],
        ),
    ]
